export enum ActionType {
  SET_DEFAULT_CITY = "SET_DEFAULT_CITY",
  SET_DETERMINED_CITY = "SET_DETERMINED_CITY",
  CHANGE_NAVIGATION_STATUS = "CHANGE_NAVIGATION_STATUS",
  SET_DETERMINED_CITY_STATUS = "SET_DETERMINED_CITY_STATUS",
  CHANGE_AVAILABLE_TIME_STATUS = "CHANGE_AVAILABLE_TIME_STATUS",
}
