export enum ActionType {
  SET_CITIES = "SET_CITIES",
  SET_CITIES_STATUS = "SET_CITIES_STATUS",
  SET_DEFAULT_CITY = "SET_DEFAULT_CITY",
  SET_DETERMINED_CITY = "SET_DETERMINED_CITY",
  CHANGE_NAVIGATION_STATUS = "CHANGE_NAVIGATION_STATUS",
  SET_DETERMINED_CITY_STATUS = "SET_DETERMINED_CITY_STATUS",
}
