export enum ActionType {
  ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  UPDATE_TOTAL_CART = "UPDATE_TOTAL_CART",
  CLEAR_CART = "CLEAR_CART",
  CHANGE_METEORS = "CHANGE_METEORS",
}
