/*
 * User constants
 */
export enum ActionType {
  SET_CATEGORIES = "SET_CATEGORIES",
  SET_CATEGORIES_STATUS = "SET_CATEGORIES_STATUS",
  SET_PRODUCTS = "SET_PRODUCTS",
  SET_PRODUCTS_STATUS = "SET_PRODUCTS_STATUS",
}
