export enum AC {
  SET_CITIES = "SET_CITIES",
  SET_CITIES_STATE = "SET_CITIES_STATE",
  SET_CATEGORIES = "SET_CATEGORIES",
  SET_CATEGORIES_STATE = "SET_CATEGORIES_STATE",
}
export enum SC {
  NOT_LOADED = "NOT_LOADED",
  LOADED = "LOADED",
  LOADING = "LOADING",
  LOADING_ERROR = "LOADING_ERROR",
}
