export enum ActionType {
  CHANGE_USER_STATE = "CHANGE_USER_STATE",
  UPDATE_USER_INFORMATION = "UPDATE_USER_INFORMATION",
  UPDATE_USER_INFORMATION_STATUS = "UPDATE_USER_INFORMATION_STATUS",
  COMPLETE_REGISTRATION = "COMPLETE_REGISTRATION",
  NEXT_REGISTRATION_STEP = "NEXT_REGISTRATION_STEP",
  SET_PHONE = "SET_PHONE",
  PREVIOUS_REGISTRATION_STEP = "PREVIOUS_REGISTRATION_STEP",
  CHANGE_PHONE_PENDING_STATE = "CHANGE_PHONE_PENDING_STATE",
  CHANGE_CODE_PENDING_STATE = "CHANGE_CODE_PENDING_STATE",
  CHANGE_LOGIN_PENDING_STATE = "CHANGE_LOGIN_PENDING_STATE",
  SET_INVITER_TOKEN = "SET_INVITER_TOKEN",
  CLEAR_USER_SESSION = "CLEAR_USER_SESSION",
}

export enum UserState {
  ANONYMOUS = "ANONYMOUS",
  WAITING_FOR_CODE = "WAITING_FOR_CODE",
  LOGGING_IN = "LOGGING_IN",
  LOGED_IN = "LOGED_IN",
}
