export enum ActionType {
  // SET_CATEGORIES = "SET_CATEGORIES",
  SET_PRODUCTS = "SET_PRODUCTS",
  SET_ERROR = "SET_ERROR",
  CLEAR_PRODUCTS = "CLEAR_PRODUCTS",
  SET_PRODUCTS_STATUS = "SET_PRODUCTS_STATUS",
}
